steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/github.com/$PROJECT_ID/bias-server:${COMMIT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/github.com/$PROJECT_ID/bias-server:${COMMIT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "bias-server",
        "--image",
        "gcr.io/$PROJECT_ID/github.com/$PROJECT_ID/bias-server:${COMMIT_SHA}",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "5000",
        "--memory",
        "2Gi"
      ]